import { ActionOptions, IntegrityItem, IntegrityItemType, MOVED_POSITION } from '@data';
import { ACTION_TYPE, ParentItemHandler } from '../../../src/service/parent-item-handler';


test('ACCEPT_MOVED_ITEMS', () => {

    const items: IntegrityItem[] = [
        {
            'id': '6035',
            'oldId': null,
            'secondaryId': null,
            'parentId': '6034',
            'category': 'Heading',
            'primarySection': '1',
            'secondarySection': '1',
            'text': '\x3C!-- MKS HTML --><h1>Introduction</h1>',
            'type': IntegrityItemType.NONE,
            'changedFields': {},
            'movedPosition': null,
            'changedAttachments': [],
            'section': '1',
        },
        {
            'id': '6042',
            'oldId': null,
            'secondaryId': null,
            'parentId': '6035',
            'category': 'Heading',
            'primarySection': '1.1',
            'secondarySection': '1.1',
            'text': '\x3C!-- MKS HTML --><h2>Background</h2>',
            'type': IntegrityItemType.NONE,
            'changedFields': {},
            'movedPosition': null,
            'changedAttachments': [],
            'section': '1.1',
        },
        {
            'id': '6036',
            'oldId': null,
            'secondaryId': '6093',
            'parentId': '6034',
            'category': 'Heading',
            'primarySection': '2',
            'secondarySection': '3',
            'text': '\x3C!-- MKS HTML --><h2>Constraints</h2>',
            'type': IntegrityItemType.MOVED,
            'changedFields': {},
            'movedPosition': MOVED_POSITION.OLD,
            'changedAttachments': [],
            'section': '2',
        },
        {
            'id': '6045',
            'oldId': null,
            'secondaryId': '6101',
            'parentId': '6036',
            'category': 'Comment',
            'primarySection': '2.1',
            'secondarySection': '3.1',
            'text': '\x3C!-- MKS HTML -->This specifies constraints on the way that the problem must be solved. Describe the mandated technology or solution. Include any appropriate version numbers. You should also explain the reason for using the technology. The constraints are treated as a type of requirement.',
            'type': IntegrityItemType.MOVED,
            'changedFields': {},
            'movedPosition': MOVED_POSITION.OLD,
            'changedAttachments': [],
            'section': '2.1',
        }, {
            'id': '6037',
            'oldId': null,
            'secondaryId': null,
            'parentId': '6034',
            'category': 'Heading',
            'primarySection': '3',
            'secondarySection': '2',
            'text': '\x3C!-- MKS HTML --><h2>Definitions</h2>',
            'type': IntegrityItemType.NONE,
            'changedFields': {},
            'movedPosition': null,
            'changedAttachments': [],
            'section': '2',
        },
        {
            'id': '6047',
            'oldId': null,
            'secondaryId': null,
            'parentId': '6037',
            'category': 'Comment',
            'primarySection': '3.1',
            'secondarySection': '2.1',
            'text': '\x3C!-- MKS HTML -->Names are very important.',
            'type': IntegrityItemType.NONE,
            'changedFields': {},
            'movedPosition': null,
            'changedAttachments': [],
            'section': '2.1',
        }, {
            'id': '6036',
            'oldId': null,
            'secondaryId': '6093',
            'parentId': '6034',
            'category': 'Heading',
            'primarySection': '2',
            'secondarySection': '3',
            'text': '\x3C!-- MKS HTML --><h2>Constraints</h2>',
            'type': IntegrityItemType.MOVED,
            'changedFields': {},
            'movedPosition': MOVED_POSITION.NEW,
            'changedAttachments': [],
            'section': '3',
        }, {
            'id': '6045',
            'oldId': null,
            'secondaryId': '6101',
            'parentId': '6036',
            'category': 'Comment',
            'primarySection': '2.1',
            'secondarySection': '3.1',
            'text': '\x3C!-- MKS HTML -->This specifies constraints on the way that the problem must be solved. Describe the mandated technology or solution. Include any appropriate version numbers. You should also explain the reason for using the technology. The constraints are treated as a type of requirement.',
            'type': IntegrityItemType.MOVED,
            'changedFields': {},
            'movedPosition': MOVED_POSITION.NEW,
            'changedAttachments': [],
            'section': '3.1',
        }, {
            'id': '6038',
            'oldId': null,
            'secondaryId': null,
            'parentId': '6034',
            'category': 'Heading',
            'primarySection': '4',
            'secondarySection': '4',
            'text': '\x3C!-- MKS HTML --><h2>Use Cases</h2>',
            'type': IntegrityItemType.NONE,
            'changedFields': {},
            'movedPosition': null,
            'changedAttachments': [],
            'section': '4',
        },

    ];
    /*
    * 2. - Parent - (moved old Position)
    *   2.1 - Child - (moved old Position)
    * 3. - Parent - (moved new Position)
    *   3.1 - Child - (moved new Position)
    * Expected:
    *   3 => accept
    *   3.1 => accept
    * */

    const documentId = '#documentId';

    const expectedResult: ActionOptions[] = [
        {
            item: items[6],
            action: ACTION_TYPE.ACCEPT,
            order: 1,
            parentInTheNewPosition: documentId,
            insertLocation: 'after:6037',
        },
        {
            item: items[7],
            action: ACTION_TYPE.ACCEPT,
            order: 2,
            parentInTheNewPosition: items[6].id,
            insertLocation: 'first',
        },

    ];


    expect(new ParentItemHandler(items, documentId).handleOptions(items[6], ACTION_TYPE.ACCEPT)).toStrictEqual(expectedResult);
});


test('ACCEPT_MOVED_ITEMS_2', () => {
    const items: IntegrityItem[] = [{
        'id': '6779',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6778',
        'category': 'Heading',
        'primarySection': '1',
        'secondarySection': '1',
        'text': '1',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '1',
    }, {
        'id': '6780',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6778',
        'category': 'Heading',
        'primarySection': '2',
        'secondarySection': '2',
        'text': '2',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '2',
    }, {
        'id': '6782',
        'oldId': null,
        'secondaryId': '6862',
        'parentId': '6778',
        'category': 'Heading',
        'primarySection': '4',
        'secondarySection': '2.1',
        'text': '2.1',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.NEW,
        'changedAttachments': [],
        'section': '2.1',
    }, {
        'id': '6793',
        'oldId': null,
        'secondaryId': '6842',
        'parentId': '6782',
        'category': 'Comment',
        'primarySection': '4.1',
        'secondarySection': '2.1.1',
        'text': '2.1.1',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.NEW,
        'changedAttachments': [],
        'section': '2.1.1',
    }, {
        'id': '6794',
        'oldId': null,
        'secondaryId': '6843',
        'parentId': '6782',
        'category': 'User Requirement',
        'primarySection': '4.2',
        'secondarySection': '2.1.2',
        'text': '2.1.2',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.NEW,
        'changedAttachments': [],
        'section': '2.1.2',
    }, {
        'id': '6795',
        'oldId': null,
        'secondaryId': '6844',
        'parentId': '6782',
        'category': 'User Requirement',
        'primarySection': '4.3',
        'secondarySection': '2.1.3',
        'text': '2.1.3',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.NEW,
        'changedAttachments': [],
        'section': '2.1.3',
    }, {
        'id': '6796',
        'oldId': null,
        'secondaryId': '6845',
        'parentId': '6782',
        'category': 'User Requirement',
        'primarySection': '4.4',
        'secondarySection': '2.1.4',
        'text': '2.1.4',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.NEW,
        'changedAttachments': [],
        'section': '2.1.4',
    }, {
        'id': '6789',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6780',
        'category': 'Comment',
        'primarySection': '2.1',
        'secondarySection': '2.2',
        'text': '2.2',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '2.2',
    }, {
        'id': '6781',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6778',
        'category': 'Heading',
        'primarySection': '3',
        'secondarySection': '3',
        'text': '3',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '3',
    }, {
        'id': '6782',
        'oldId': null,
        'secondaryId': '6862',
        'parentId': '6778',
        'category': 'Heading',
        'primarySection': '4',
        'secondarySection': '2.1',
        'text': '4',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.OLD,
        'changedAttachments': [],
        'section': '4',
    }, {
        'id': '6793',
        'oldId': null,
        'secondaryId': '6842',
        'parentId': '6782',
        'category': 'Comment',
        'primarySection': '4.1',
        'secondarySection': '2.1.1',
        'text': '4.1',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.OLD,
        'changedAttachments': [],
        'section': '4.1',
    }, {
        'id': '6794',
        'oldId': null,
        'secondaryId': '6843',
        'parentId': '6782',
        'category': 'User Requirement',
        'primarySection': '4.2',
        'secondarySection': '2.1.2',
        'text': '4.2',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.OLD,
        'changedAttachments': [],
        'section': '4.2',
    }, {
        'id': '6795',
        'oldId': null,
        'secondaryId': '6844',
        'parentId': '6782',
        'category': 'User Requirement',
        'primarySection': '4.3',
        'secondarySection': '2.1.3',
        'text': '4.3',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.OLD,
        'changedAttachments': [],
        'section': '4.3',
    }, {
        'id': '6796',
        'oldId': null,
        'secondaryId': '6845',
        'parentId': '6782',
        'category': 'User Requirement',
        'primarySection': '4.4',
        'secondarySection': '2.1.4',
        'text': '4.4',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.OLD,
        'changedAttachments': [],
        'section': '4.4',
    }, {
        'id': '6783',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6778',
        'category': 'Heading',
        'primarySection': '5',
        'secondarySection': '4',
        'text': '4',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '4',
    }, {
        'id': '6798',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6783',
        'category': 'Comment',
        'primarySection': '5.1',
        'secondarySection': '4.1',
        'text': '4.1',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '4.1',
    }, {
        'id': '6799',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6783',
        'category': 'System Requirement',
        'primarySection': '5.2',
        'secondarySection': '4.2',
        'text': '4.2',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '4.2',
    }, {
        'id': '6800',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6783',
        'category': 'System Requirement',
        'primarySection': '5.3',
        'secondarySection': '4.3',
        'text': '4.3',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '4.3',
    }, {
        'id': '6801',
        'oldId': null,
        'secondaryId': null,
        'parentId': '6783',
        'category': 'System Requirement',
        'primarySection': '5.4',
        'secondarySection': '4.4',
        'text': '4.4',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '4.4',
    },
    ];

    const documentId = '#documentId';

    const expectedResult: ActionOptions[] = [
        {
            item: items[2],
            action: ACTION_TYPE.ACCEPT,
            order: 1,
            parentInTheNewPosition: items[1].id,
            insertLocation: 'first',
        },
        {
            item: items[3],
            action: ACTION_TYPE.ACCEPT,
            order: 2,
            parentInTheNewPosition: items[2].id,
            insertLocation: 'first',
        },
        {
            item: items[4],
            action: ACTION_TYPE.ACCEPT,
            order: 3,
            parentInTheNewPosition: items[2].id,
            insertLocation: 'after:' + items[3].id,
        },
        {
            item: items[5],
            action: ACTION_TYPE.ACCEPT,
            order: 4,
            parentInTheNewPosition: items[2].id,
            insertLocation: 'after:' + items[4].id,
        },
        {
            item: items[6],
            action: ACTION_TYPE.ACCEPT,
            order: 5,
            parentInTheNewPosition: items[2].id,
            insertLocation: 'after:' + items[5].id,
        },

    ];


    expect(new ParentItemHandler(items, documentId).handleOptions(items[2], ACTION_TYPE.ACCEPT)).toStrictEqual(expectedResult);

});
