import { ACTION_TYPE, ParentItemHandler } from '../../../src/service/parent-item-handler';
import { ActionOptions, IntegrityItem, IntegrityItemType, MOVED_POSITION } from '@data';

describe('deep nesting of added items', () => {

    const items: IntegrityItem[] = [{
        'id': '7750',
        'oldId': null,
        'secondaryId': null,
        'parentId': '7741',
        'category': 'Functional Requirement',
        'primarySection': null,
        'secondarySection': '1',
        'text': '1',
        'type': IntegrityItemType.NEW,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '1',
    }, {
        'id': '7752',
        'oldId': null,
        'secondaryId': null,
        'parentId': '7750',
        'category': 'Functional Requirement',
        'primarySection': null,
        'secondarySection': '1.1',
        'text': '1.1',
        'type': IntegrityItemType.NEW,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '1.1',
    }, {
        'id': '7727',
        'oldId': null,
        'secondaryId': '7749',
        'parentId': '7726',
        'category': 'Heading',
        'primarySection': '1.1.1',
        'secondarySection': '1.1.1',
        'text': '1.1.1',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.NEW,
        'changedAttachments': [],
        'section': '1.1.1',
    }, {
        'id': '7734',
        'oldId': null,
        'secondaryId': '7746',
        'parentId': '7727',
        'category': 'Comment',
        'primarySection': '1.1.1.1',
        'secondarySection': '1.1.1.1',
        'text': '1.1.1.1',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.NEW,
        'changedAttachments': [],
        'section': '1.1.1.1',
    }, {
        'id': '7754',
        'oldId': null,
        'secondaryId': null,
        'parentId': '7752',
        'category': 'Functional Requirement',
        'primarySection': null,
        'secondarySection': '1.1.2',
        'text': '1.1.2',
        'type': IntegrityItemType.NEW,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '1.1.2',
    }, {
        'id': '7725',
        'oldId': null,
        'secondaryId': null,
        'parentId': '7724',
        'category': 'Heading',
        'primarySection': '1',
        'secondarySection': '2',
        'text': '2',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '2',
    }, {
        'id': '7726',
        'oldId': null,
        'secondaryId': null,
        'parentId': '7725',
        'category': 'Heading',
        'primarySection': '1.1',
        'secondarySection': '2.1',
        'text': '2.1',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '2.1',
    }, {
        'id': '7727',
        'oldId': null,
        'secondaryId': '7749',
        'parentId': '7726',
        'category': 'Heading',
        'primarySection': '1.1.1',
        'secondarySection': '1.1.1',
        'text': '2.1.1',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.OLD,
        'changedAttachments': [],
        'section': '2.1.1',
    }, {
        'id': '7734',
        'oldId': null,
        'secondaryId': '7746',
        'parentId': '7727',
        'category': 'Comment',
        'primarySection': '1.1.1.1',
        'secondarySection': '1.1.1.1',
        'text': '2.1.1.1',
        'type': IntegrityItemType.MOVED,
        'changedFields': {},
        'movedPosition': MOVED_POSITION.OLD,
        'changedAttachments': [],
        'section': '2.1.1.1',
    }, {
        'id': '7732',
        'oldId': null,
        'secondaryId': null,
        'parentId': '7726',
        'category': 'Comment',
        'primarySection': '1.1.2',
        'secondarySection': '2.1.1',
        'text': '2.1.1',
        'type': IntegrityItemType.NONE,
        'changedFields': {},
        'movedPosition': null,
        'changedAttachments': [],
        'section': '2.1.1',
    }];


    test('decline all items', () => {

        const expectedResult: ActionOptions[] = [
            {
                item: items[0],
                action: ACTION_TYPE.DECLINE,
                order: 1,
                parentInTheNewPosition: null,
                insertLocation: null,
            },
            {
                item: items[1],
                action: ACTION_TYPE.DECLINE,
                order: 2,
                parentInTheNewPosition: null,
                insertLocation: null,
            },
            {
                item: items[7],
                action: ACTION_TYPE.DECLINE,
                order: 3,
                parentInTheNewPosition: null,
                insertLocation: null,
            },
            {
                item: items[8],
                action: ACTION_TYPE.DECLINE,
                order: 4,
                parentInTheNewPosition: null,
                insertLocation: null,
            },
            {
                item: items[4],
                action: ACTION_TYPE.DECLINE,
                order: 5,
                parentInTheNewPosition: null,
                insertLocation: null,
            },
        ];
        const result = new ParentItemHandler(items, 'document').handleOptions(items[0], ACTION_TYPE.DECLINE);
        expect(result).toStrictEqual(expectedResult);
    });

});
